import { Product } from "./types/Product";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "PORTAIL COULISSANT 3M VEYMONT H.140CM ALUMINIUM GRIS",
    price: 699,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 2,
    name: "PORTILLONS COULISSANT 3M VOGEL H.140CM ALUMINIUM GRIS",
    price: 719,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portillons",
  },
  {
    id: 3,
    name: "PORTAIL COULISSANT 3M EIGER H.140CM ALUMINIUM GRIS",
    price: 759,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 4,
    name: "PORTILLONS COULISSANT 3M CIMONE H.140 ALUMINIUM GRIS",
    price: 759,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portillons",
  },
  {
    id: 5,
    name: "PORTAIL COULISSANT 3,5M VEYMONT H.140CM ALUMINIUM GRIS",
    price: 789,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 6,
    name: "PORTAIL COULISSANT 3,5M VOGEL H.140CM ALUMINIUM GRIS",
    price: 799,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 7,
    name: "PORTAIL COULISSANT 3M VEYMONT H.160CM ALUMINIUM GRIS",
    price: 799,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 8,
    name: "PORTAIL COULISSANT 3M VOGEL H.160CM ALUMINIUM GRIS",
    price: 2819,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 9,
    name: "PORTAIL COULISSANT 3,5M EIGER H.140CM ALUMINIUM GRIS",
    price: 859,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 10,
    name: "PORTAIL COULISSANT 4M VEYMONT H.160CM ALUMINIUM GRIS",
    price: 899,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 11,
    name: "PORTAIL COULISSANT 4M VOGEL H.160CM ALUMINIUM GRIS",
    price: 1949,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 12,
    name: "PORTAIL COULISSANT 4M EIGER H.180CM ALUMINIUM GRIS",
    price: 999,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 13,
    name: "PORTAIL COULISSANT 4,5M VEYMONT H.160CM ALUMINIUM GRIS",
    price: 1049,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 14,
    name: "PORTAIL COULISSANT 4,5M VOGEL H.160CM ALUMINIUM GRIS",
    price: 1099,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 15,
    name: "PORTAIL COULISSANT 5M VEYMONT H.180CM ALUMINIUM GRIS",
    price: 1149,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 16,
    name: "PORTAIL COULISSANT 5M VOGEL H.180CM ALUMINIUM GRIS",
    price: 1199,
    imageUrls: ["https://placehold.co/600x400"],
    category: "portails",
  },
  {
    id: 17,
    name: "PERGOLA ALUMINIUM 3X3M GRIS ANTHRACITE",
    price: 1199,
    imageUrls: ["https://placehold.co/600x400"],
    category: "pergolas",
  },
  {
    id: 18,
    name: "PERGOLA ALUMINIUM 3X4M GRIS ANTHRACITE",
    price: 1249,
    imageUrls: ["https://placehold.co/600x400"],
    category: "pergolas",
  },
  {
    id: 19,
    name: "PERGOLA ALUMINIUM 3X5M GRIS ANTHRACITE",
    price: 1299,
    imageUrls: ["https://placehold.co/600x400"],
    category: "pergolas",
  },
  {
    id: 20,
    name: "PERGOLA ALUMINIUM 3X6M GRIS ANTHRACITE",
    price: 1349,
    imageUrls: ["https://placehold.co/600x400"],
    category: "pergolas",
  },
  {
    id: 21,
    name: "PERGOLA ALUMINIUM 3X7M GRIS ANTHRACITE",
    price: 1399,
    imageUrls: ["https://placehold.co/600x400"],
    category: "pergolas",
  },
  {
    id: 22,
    name: "PERGOLA ALUMINIUM 3X8M GRIS ANTHRACITE",
    price: 1449,
    imageUrls: ["https://placehold.co/600x400"],
    category: "pergolas",
  },
  {
    id: 23,
    name: "PERGOLA ALUMINIUM 3X9M GRIS ANTHRACITE",
    price: 1499,
    imageUrls: ["https://placehold.co/600x400"],
    category: "pergolas",
  },
  {
    id: 24,
    name: "PERGOLA ALUMINIUM 3X10M GRIS ANTHRACITE",
    price: 1549,
    imageUrls: ["https://placehold.co/600x400"],
    category: "pergolas",
  },
];
